hash-format = "sha256"

[[files]]
file = "README.md"

[[files]]
file = "modrinth.index.json"

[[files]]
file = "mods/almanac.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/get-it-together-drops.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/mousetweaks-x-accessories-fix.pw.toml"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
metafile = true

[[files]]
file = "mods/sable.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "overrides/README.md"

[[files]]
file = "overrides/overrides/README.md"
