name = "Aeronautics"
author = "Teodor"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
no-internal-hashes = true
